name: Unpack kiss2gocomplet.zip and Build Kiss2Go APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Unzip kiss2gocomplet.zip
      run: |
        mkdir unzipped
        unzip kiss2gocomplet.zip -d unzipped

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Find gradlew path
      id: find_gradlew
      run: |
        echo "GRADLEW_PATH=$(find ./unzipped -name gradlew -type f)" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x $GRADLEW_PATH

    - name: Build Debug APK
      run: |
        cd $(dirname $GRADLEW_PATH)
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kiss2Go-APK
        path: '**/app/build/outputs/apk/debug/app-debug.apk'
