name: Unpack app.zip and Build Kiss2Go APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unzip Kiss2Gofull.zip
        run: unzip -o Kiss2Gofull.zip -d .

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./Kiss2Gofull/gradlew

      - name: Build Debug APK
        run: ./Kiss2Gofull/gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiss2go-apk
          path: Kiss2Gofull/app/build/outputs/apk/debug/app-debug.apk
